language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - wget https://drive.google.com/uc?id=1NPdjByLedmQPWNdq9hmWgmFpStvERfla -O ltdb_sample.zip
  - wget https://drive.google.com/uc?id=1uBvcbhILa1eiSFgNSTc1XteVyWzJjpcK -O ltdb_full.zip
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export DLPATH=`pwd`
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes pytables
  - conda install --yes cython
  - pip install -r requirements.txt

script:
  - python setup.py sdist >/dev/null
  - pytest --ignore=examples --ignore=osnap/visualization

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - suhanmappingideas@gmail.com
            - weikang9009@gmail.com
            - levi.john.wolf@gmail.com
            - ek@knaaptime.com 
        on_success: change
        on_failure: always 

after_success:
  - coveralls
