language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - wget https://www.dropbox.com/s/i2he4wm0pkgg55t/LTDB_Std_All_Sample.zip?dl=1 -O ltdb_sample.zip
  - wget https://www.dropbox.com/s/np7a9ma5pd6m09p/LTDB_Std_All_fullcount.zip?dl=1 -O ltdb_full.zip
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export DLPATH=`pwd`
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes pip
  - conda env create -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - source activate osnap
  - pip install python-coveralls
  - pip install pytest-cov


script:
  - python setup.py sdist >/dev/null
  - pytest --ignore=examples --ignore=osnap/util  --cov osnap

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - suhanmappingideas@gmail.com
            - weikang9009@gmail.com
            - levi.john.wolf@gmail.com
            - ek@knaaptime.com 
        on_success: change
        on_failure: always 

after_success:
  - coveralls
