name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy >=2.2.1
  - libpysal
  - spenc
  - cenpy
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow =0.13
  - appdirs
  - dash
  - dash-bootstrap-components
  - palettable
  - pip
  - tqdm
  - quilt3
  - xlrd
  - pip:
    - git+git://github.com/pysal/region@master
    - git+git://github.com/pysal/tobler@master
