name: geosnap
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - cython
  - geopandas
  - hdbscan
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow =0.13
  - appdirs
  - pip
  - pip:
    - libpysal
    - mapclassify
    - spenc
    - giddy
    - xlrd
    - cenpy
    - quilt3
    - git+git://github.com/pysal/region@master
