name: osnap
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - geopandas
  - hdbscan
  - matplotlib
  - notebook
  - networkx
  - pysal
  - scikit-learn
  - pyarrow
  - pip
  - pip:
    - libpysal
    - mapclassify
    - region
    - spenc
    - giddy
    - xlrd
    - cenpy
