name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy
  - libpysal
  - spenc
  - cenpy
  - cython
  - geopandas
  - hdbscan
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow=0.13
  - appdirs
  - dash
  - dash-bootstrap-components
  - palettable
  - pip
  - tqdm
  - pip:
    - xlrd
    - quilt3
    - git+git://github.com/pysal/region@master
